name: pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - name: Install dependencies
        run: |
          sudo apt-get install cppcheck -y
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
      - uses: pre-commit/action@v2.0.0
